### ISSUE TITLE
TOKEN_DECIPHER_KEY

### ISSUE THREAD

**Issue by 89z** [MACJIO/deeZZer#2]
Where to get this:

https://github.com/MACJIO/deeZZer/blob/52abf460034f2dcd40d5def25e924152f55ec5fb/src/utils.ts#L42-L44

**Comment by MACJIO** [comment]
Hey. U can find in application code. For the current version of the project I used this:  
`"TOKEN_DECIPHER_KEY": "VBK1FSUEXHTSDBJJ"`

**Comment by MACJIO** [comment]
Here is the complete config, it will be easier for you. But I repeat that this project was tested only on older versions of the application.

```
{
  "APP": {
    "ANDROID_API_KEY": "4VCYIJUCDLOUELGD1V8WBVYBNVDYOXEWSLLZDONGBBDFVXTZJRXPR29JRLQFO6ZE",
    "IOS_API_KEY": "ZAIVAHCEISOHWAICUQUEXAEPICENGUAFAEZAIPHAELEEVAHPHUCUFONGUAPASUAY",
    "HTTP_API_URL": "http://api.deezer.com/1.0/",
    "HTTPS_API_URL": "https://api.deezer.com/1.0/",
    "HTTPS_API_URL_WITH_PORT": "https://api.deezer.com:443/1.0/",
    "TOKEN_DECIPHER_KEY": "VBK1FSUEXHTSDBJJ",
    "MUSIC_TOKEN_CIPHER_KEY": "jo6aey6haid2Teih",
    "MOBILE_TRACKING_SECRET": "deezer011013sc",
    "NETWORK_CIPHER_KEY": "a8u5.26iHgcv,OIu"
  }
}
